"""added column for vpn ip

Revision ID: 0653024a6c35
Revises: 9f76c7aa0658
Create Date: 2018-05-03 20:16:34.520380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0653024a6c35'
down_revision = '9f76c7aa0658'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('vpn_ipv4', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('server', 'vpn_ipv4')
    # ### end Alembic commands ###
