"""added Server.external_ipv4

Revision ID: a7126a0a20ae
Revises: 0653024a6c35
Create Date: 2018-05-12 20:21:46.035162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7126a0a20ae'
down_revision = '0653024a6c35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('external_ipv4', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('server', 'external_ipv4')
    # ### end Alembic commands ###
